//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZCWelder.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("王欢")]
        public string Corrector {
            get {
                return ((string)(this["Corrector"]));
            }
            set {
                this["Corrector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Assessor {
            get {
                return ((string)(this["Assessor"]));
            }
            set {
                this["Assessor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Rehear {
            get {
                return ((string)(this["Rehear"]));
            }
            set {
                this["Rehear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultUsername {
            get {
                return ((string)(this["DefaultUsername"]));
            }
            set {
                this["DefaultUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("傅玉华")]
        public string Lister {
            get {
                return ((string)(this["Lister"]));
            }
            set {
                this["Lister"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("沪东中华造船（集团）有限公司")]
        public string Company {
            get {
                return ((string)(this["Company"]));
            }
            set {
                this["Company"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppRole {
            get {
                return ((string)(this["AppRole"]));
            }
            set {
                this["AppRole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppRolePassword {
            get {
                return ((string)(this["AppRolePassword"]));
            }
            set {
                this["AppRolePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("宋体, 9pt")]
        public global::System.Drawing.Font FormFont {
            get {
                return ((global::System.Drawing.Font)(this["FormFont"]));
            }
            set {
                this["FormFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color FormBackColor {
            get {
                return ((global::System.Drawing.Color)(this["FormBackColor"]));
            }
            set {
                this["FormBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color textBoxDoubleClickColor {
            get {
                return ((global::System.Drawing.Color)(this["textBoxDoubleClickColor"]));
            }
            set {
                this["textBoxDoubleClickColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color GridColor {
            get {
                return ((global::System.Drawing.Color)(this["GridColor"]));
            }
            set {
                this["GridColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color DataGridViewBackColor {
            get {
                return ((global::System.Drawing.Color)(this["DataGridViewBackColor"]));
            }
            set {
                this["DataGridViewBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color DataGridViewAlternatingBackColor {
            get {
                return ((global::System.Drawing.Color)(this["DataGridViewAlternatingBackColor"]));
            }
            set {
                this["DataGridViewAlternatingBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TheoryTeacherID {
            get {
                return ((string)(this["TheoryTeacherID"]));
            }
            set {
                this["TheoryTeacherID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArchiveTeacherID {
            get {
                return ((string)(this["ArchiveTeacherID"]));
            }
            set {
                this["ArchiveTeacherID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IssueQCTeacherID {
            get {
                return ((string)(this["IssueQCTeacherID"]));
            }
            set {
                this["IssueQCTeacherID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SupervisorID {
            get {
                return ((string)(this["SupervisorID"]));
            }
            set {
                this["SupervisorID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SkillTeacherID {
            get {
                return ((string)(this["SkillTeacherID"]));
            }
            set {
                this["SkillTeacherID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal OriginalPeriod {
            get {
                return ((decimal)(this["OriginalPeriod"]));
            }
            set {
                this["OriginalPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2011-02-15")]
        public global::System.DateTime IssuedOn {
            get {
                return ((global::System.DateTime)(this["IssuedOn"]));
            }
            set {
                this["IssuedOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color splitContainerHeadBackColor {
            get {
                return ((global::System.Drawing.Color)(this["splitContainerHeadBackColor"]));
            }
            set {
                this["splitContainerHeadBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color splitContainerHeadForeColor {
            get {
                return ((global::System.Drawing.Color)(this["splitContainerHeadForeColor"]));
            }
            set {
                this["splitContainerHeadForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SH11")]
        public string CCSTestCommitteeID {
            get {
                return ((string)(this["CCSTestCommitteeID"]));
            }
            set {
                this["CCSTestCommitteeID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("沪东中华造船（集团）焊工考试委员会")]
        public string CCSTestCommittee {
            get {
                return ((string)(this["CCSTestCommittee"]));
            }
            set {
                this["CCSTestCommittee"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WebServiceStartUp {
            get {
                return ((bool)(this["WebServiceStartUp"]));
            }
            set {
                this["WebServiceStartUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("021-58713222-3706")]
        public string LinkTel {
            get {
                return ((string)(this["LinkTel"]));
            }
            set {
                this["LinkTel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal PeriodofProlongation {
            get {
                return ((decimal)(this["PeriodofProlongation"]));
            }
            set {
                this["PeriodofProlongation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("浦东大道2851号")]
        public string MailEmployerAddress {
            get {
                return ((string)(this["MailEmployerAddress"]));
            }
            set {
                this["MailEmployerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("沪东中华造船（集团）有限公司")]
        public string MailEmployer {
            get {
                return ((string)(this["MailEmployer"]));
            }
            set {
                this["MailEmployer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200129")]
        public string MailEmployerPostalcode {
            get {
                return ((string)(this["MailEmployerPostalcode"]));
            }
            set {
                this["MailEmployerPostalcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.30.1.4/HPWelderPictures/WelderPicture.asmx")]
        public string 江南造船焊工信息管理软件_ZCWelderPicture_WelderPicture {
            get {
                return ((string)(this["江南造船焊工信息管理软件_ZCWelderPicture_WelderPicture"]));
            }
            set {
                this["江南造船焊工信息管理软件_ZCWelderPicture_WelderPicture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color WPSLockedColor {
            get {
                return ((global::System.Drawing.Color)(this["WPSLockedColor"]));
            }
            set {
                this["WPSLockedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color notSupervisionColor {
            get {
                return ((global::System.Drawing.Color)(this["notSupervisionColor"]));
            }
            set {
                this["notSupervisionColor"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\sqlexpress;Initial Catalog=ZCWelder;Integrated Security=Tru" +
            "e;Min Pool Size=1")]
        public string zwjConn {
            get {
                return ((string)(this["zwjConn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\sqlexpress;Initial Catalog=hdhr;Integrated Security=True")]
        public string zwjConnhdhr {
            get {
                return ((string)(this["zwjConnhdhr"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("沪东中华")]
        public string PlaceofTest {
            get {
                return ((string)(this["PlaceofTest"]));
            }
            set {
                this["PlaceofTest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("沪东中华")]
        public string SupervisionPlace {
            get {
                return ((string)(this["SupervisionPlace"]));
            }
            set {
                this["SupervisionPlace"] = value;
            }
        }
    }
}
